ldap_sso.settings:
  type: config_object
  mapping:
    ssoRemoteUserStripDomainName:
      type: integer
    ssoExcludedPaths:
      type: sequence
      sequence:
        type: string
    ssoExcludedHosts:
      type: sequence
      sequence:
        type: string
    seamlessLogin:
      type: string
    ldapImplementation:
      type: string
    cookieExpire:
      type: string
