<?php

/**
 * @file
 * This module injects itself into Drupal's Authentication stack.
 */

use Drupal\Core\Url;
use Drupal\ldap_sso\LdapSsoInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_user_logout().
 */
function ldap_sso_user_logout($account) {

  if (\Drupal::config('ldap_sso.settings')->get('seamlessLogin') == 1) {
    if (\Drupal::config('ldap_sso.settings')->get('cookieExpire') == -1) {
      // Length of session.
      $cookie_lifetime = 0;
    }
    else {
      // A value quickly in the past.
      $cookie_lifetime = time();
    }
    setcookie('seamless_login', LdapSsoInterface::AUTO_LOGIN_NO, $cookie_lifetime, base_path(), '');
  }
  $redirect = new RedirectResponse(Url::fromRoute('user.login')->toString());
  $redirect->send();
}
