<?php

/**
 * @file
 * Contains ug_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ug_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ug_page module.
    case 'help.page.ug_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UG Page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ug_page_theme() {
  return [
    'ug_page' => [
      'render element' => 'children',
    ],
  ];
}
