#!/bin/bash

# Safe mode
set -xeuo pipefail

# Environment
SITE=${SITE:-ug-avalon}
ENV=${ENV:-dev}
TEMP=${TEMP:-/tmp}
UPSTREAM_URL=https://oauth:$SYSTEM_ACCESSTOKEN@ccswds.visualstudio.com/_git/Avalon
RELEASE=${BUILD_SOURCEVERSION:-master}

# Clone site repository
cd $TEMP
rm -rf $SITE
GIT_URL=$(terminus connection:info $SITE.$ENV --field=git_url)
git clone $GIT_URL $SITE

# Merge release tag/commit
cd $SITE
git remote add upstream $UPSTREAM_URL
git fetch upstream
git rebase upstream/master
git push origin HEAD

# Rollback previous migration
terminus drush $SITE.$ENV -- migrate-rollback --group=migrate_drupal_7 </dev/null || true

# Import config
terminus drush $SITE.$ENV -- config-import -y </dev/null

# Migrate content
terminus drush $SITE.$ENV -- migrate-import --group=migrate_drupal_7 </dev/null || true
terminus drush $SITE.$ENV -- migrate-import --group=migrate_drupal_7 --update </dev/null || true

