#!/bin/bash

# Safe mode
set -xeuo pipefail

# Utilities
PATH=$PATH:/opt/terminus/vendor/bin

# Environment
SITE=${SITE:-ug-avalon}
ENV=${ENV:-live}

# Deploy to Pantheon live environment
terminus env:deploy $SITE.$ENV --updatedb </dev/null

