<?php

/**
 * @file
 * Contains ug_profile.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ug_profile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ug_profile module.
    case 'help.page.ug_profile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UG Profile') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ug_profile_theme() {
  return [
    'ug_profile' => [
      'render element' => 'children',
    ],
  ];
}
